#cloud-config
# The top level settings are used as module
# and system configuration.

# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
 - default

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the above user (fedora).
disable_root: false

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

mount_default_fields: [~, ~, 'auto', 'defaults,nofail', '0', '2']
ssh_deletekeys:   0
ssh_genkeytypes:  ~
syslog_fix_perms: ~


# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
  # This will affect which distro class gets used
  distro: fedora
  # Default user name + that default user's groups
  default_user:
    name: cloud
    lock_passwd: true
    gecos: Fedora
    groups: [wheel, adm, systemd-journal]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
  paths:
    cloud_dir: /var/lib/cloud
    templates_dir: /etc/cloud/templates
  ssh_svcname: sshd
# vim:syntax=yaml
